### ISSUE TITLE
Error after logging in 

### ISSUE THREAD

**Issue by ctrlcmdshft** [henningBunk/bitwarden-dl#1]
When running i get this Error below

```
python ./bitwarden-dl.py
Please enter your Bitwarden API client ID:
Please enter your API client secret:
Please enter your Bitwarden master password:
Logging into your vault...
Traceback (most recent call last):
  File "C:\Users\username\Desktop\bitwarden-dl-main\bitwarden-dl.py", line 224, in <module>
    main()
  File "C:\Users\username\Desktop\bitwarden-dl-main\bitwarden-dl.py", line 17, in main
    bw = Bitwarden(id, secret, password)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\Desktop\bitwarden-dl-main\bitwarden-dl.py", line 127, in __init__
    subprocess.check_output([
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by henningBunk** [comment]
Hey!
I forgot a very important step in my installation instructions. The scripts calls the Bitwarden CLI. Do you have this available? If not, please do so and test again:

https://bitwarden.com/help/cli/#download-and-install

Sorry for that. Hope this helps, if not please let me know.

**Comment by ctrlcmdshft** [comment]
That did it, thanks worked like a charm
